version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-website:latest
    container_name: my-website
    restart: unless-stopped
    ports:
      - "9090:80"
    volumes:
      - . /var/www/html/
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "tdent"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
